[COMPILATION]
mock = false

[ANALYSIS]
cost_key = ["fake_result_multishot", "y"]
maximize = true
ignore_bad = true
analysislib_console_log_level = 20
analysislib_file_log_level = 10
groups = ["Imaging"]

[MLOOP]
training_type = "random"
num_training_runs = 2
max_num_runs_without_better_params = 10
max_num_runs = 5
max_duration = 3600
trust_region = 0.5
cost_has_noise = true
no_delay = false
visualisations = false
controller_type = "gaussian_process"
console_log_level = 10
# filename prefix for controller archive, can include path
controller_archive_filename = "X:\\userlib\\analysislib\\analysislib-mloop\\controller-archives\\"
controller_archive_file_type = "txt"
# filename prefix for learner archive, can include path
learner_archive_filename = "X:\\userlib\\analysislib\\analysislib-mloop\\learner-archives\\"
learner_archive_file_type = "txt"

# Automatically creates the mapping to a runmanager global
[MLOOP_PARAMS.Imaging.x] # this is part of the MOT group 
global_name = "x"  # << Specify the runmanager global it maps to
min = -5.0
max = 5.0
start = -2
